package com.tony.proto.pojo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Point2PointMessage.proto

public final class Point2PointMessageOuterClass {
    private Point2PointMessageOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface Point2PointMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Point2PointMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes java_class = 127;</code>
         *
         * @return The javaClass.
         */
        com.google.protobuf.ByteString getJavaClass();

        /**
         * <code>string targetAddressKey = 1;</code>
         *
         * @return The targetAddressKey.
         */
        String getTargetAddressKey();

        /**
         * <code>string targetAddressKey = 1;</code>
         *
         * @return The bytes for targetAddressKey.
         */
        com.google.protobuf.ByteString
        getTargetAddressKeyBytes();

        /**
         * <code>string message = 2;</code>
         *
         * @return The message.
         */
        String getMessage();

        /**
         * <code>string message = 2;</code>
         *
         * @return The bytes for message.
         */
        com.google.protobuf.ByteString
        getMessageBytes();
    }

    /**
     * Protobuf type {@code Point2PointMessage}
     */
    public static final class Point2PointMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Point2PointMessage)
            Point2PointMessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Point2PointMessage.newBuilder() to construct.
        private Point2PointMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Point2PointMessage() {
            javaClass_ = com.google.protobuf.ByteString.EMPTY;
            targetAddressKey_ = "";
            message_ = "";
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new Point2PointMessage();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Point2PointMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            targetAddressKey_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                        case 1018: {

                            javaClass_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Point2PointMessageOuterClass.internal_static_Point2PointMessage_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Point2PointMessageOuterClass.internal_static_Point2PointMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Point2PointMessage.class, Builder.class);
        }

        public static final int JAVA_CLASS_FIELD_NUMBER = 127;
        private com.google.protobuf.ByteString javaClass_;

        /**
         * <code>bytes java_class = 127;</code>
         *
         * @return The javaClass.
         */
        @Override
        public com.google.protobuf.ByteString getJavaClass() {
            return javaClass_;
        }

        public static final int TARGETADDRESSKEY_FIELD_NUMBER = 1;
        private volatile Object targetAddressKey_;

        /**
         * <code>string targetAddressKey = 1;</code>
         *
         * @return The targetAddressKey.
         */
        @Override
        public String getTargetAddressKey() {
            Object ref = targetAddressKey_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                targetAddressKey_ = s;
                return s;
            }
        }

        /**
         * <code>string targetAddressKey = 1;</code>
         *
         * @return The bytes for targetAddressKey.
         */
        @Override
        public com.google.protobuf.ByteString
        getTargetAddressKeyBytes() {
            Object ref = targetAddressKey_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                targetAddressKey_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int MESSAGE_FIELD_NUMBER = 2;
        private volatile Object message_;

        /**
         * <code>string message = 2;</code>
         *
         * @return The message.
         */
        @Override
        public String getMessage() {
            Object ref = message_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>string message = 2;</code>
         *
         * @return The bytes for message.
         */
        @Override
        public com.google.protobuf.ByteString
        getMessageBytes() {
            Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTargetAddressKeyBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, targetAddressKey_);
            }
            if (!getMessageBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
            }
            if (!javaClass_.isEmpty()) {
                output.writeBytes(127, javaClass_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!getTargetAddressKeyBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, targetAddressKey_);
            }
            if (!getMessageBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
            }
            if (!javaClass_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(127, javaClass_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Point2PointMessage)) {
                return super.equals(obj);
            }
            Point2PointMessage other = (Point2PointMessage) obj;

            if (!getJavaClass()
                    .equals(other.getJavaClass())) {
                return false;
            }
            if (!getTargetAddressKey()
                    .equals(other.getTargetAddressKey())) {
                return false;
            }
            if (!getMessage()
                    .equals(other.getMessage())) {
                return false;
            }
            if (!unknownFields.equals(other.unknownFields)) {
                return false;
            }
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + JAVA_CLASS_FIELD_NUMBER;
            hash = (53 * hash) + getJavaClass().hashCode();
            hash = (37 * hash) + TARGETADDRESSKEY_FIELD_NUMBER;
            hash = (53 * hash) + getTargetAddressKey().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Point2PointMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Point2PointMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Point2PointMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Point2PointMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Point2PointMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Point2PointMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Point2PointMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Point2PointMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Point2PointMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Point2PointMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Point2PointMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Point2PointMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Point2PointMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Point2PointMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Point2PointMessage)
                Point2PointMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Point2PointMessageOuterClass.internal_static_Point2PointMessage_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Point2PointMessageOuterClass.internal_static_Point2PointMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Point2PointMessage.class, Builder.class);
            }

            // Construct using Point2PointMessageOuterClass.Point2PointMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                javaClass_ = com.google.protobuf.ByteString.EMPTY;

                targetAddressKey_ = "";

                message_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Point2PointMessageOuterClass.internal_static_Point2PointMessage_descriptor;
            }

            @Override
            public Point2PointMessage getDefaultInstanceForType() {
                return Point2PointMessage.getDefaultInstance();
            }

            @Override
            public Point2PointMessage build() {
                Point2PointMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Point2PointMessage buildPartial() {
                Point2PointMessage result = new Point2PointMessage(this);
                result.javaClass_ = javaClass_;
                result.targetAddressKey_ = targetAddressKey_;
                result.message_ = message_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Point2PointMessage) {
                    return mergeFrom((Point2PointMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Point2PointMessage other) {
                if (other == Point2PointMessage.getDefaultInstance()) {
                    return this;
                }
                if (other.getJavaClass() != com.google.protobuf.ByteString.EMPTY) {
                    setJavaClass(other.getJavaClass());
                }
                if (!other.getTargetAddressKey().isEmpty()) {
                    targetAddressKey_ = other.targetAddressKey_;
                    onChanged();
                }
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Point2PointMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Point2PointMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.ByteString javaClass_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes java_class = 127;</code>
             *
             * @return The javaClass.
             */
            @Override
            public com.google.protobuf.ByteString getJavaClass() {
                return javaClass_;
            }

            /**
             * <code>bytes java_class = 127;</code>
             *
             * @param value The javaClass to set.
             * @return This builder for chaining.
             */
            public Builder setJavaClass(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                javaClass_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes java_class = 127;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearJavaClass() {

                javaClass_ = getDefaultInstance().getJavaClass();
                onChanged();
                return this;
            }

            private Object targetAddressKey_ = "";

            /**
             * <code>string targetAddressKey = 1;</code>
             *
             * @return The targetAddressKey.
             */
            @Override
            public String getTargetAddressKey() {
                Object ref = targetAddressKey_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    targetAddressKey_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string targetAddressKey = 1;</code>
             *
             * @return The bytes for targetAddressKey.
             */
            @Override
            public com.google.protobuf.ByteString
            getTargetAddressKeyBytes() {
                Object ref = targetAddressKey_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    targetAddressKey_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string targetAddressKey = 1;</code>
             *
             * @param value The targetAddressKey to set.
             * @return This builder for chaining.
             */
            public Builder setTargetAddressKey(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                targetAddressKey_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string targetAddressKey = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTargetAddressKey() {

                targetAddressKey_ = getDefaultInstance().getTargetAddressKey();
                onChanged();
                return this;
            }

            /**
             * <code>string targetAddressKey = 1;</code>
             *
             * @param value The bytes for targetAddressKey to set.
             * @return This builder for chaining.
             */
            public Builder setTargetAddressKeyBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                targetAddressKey_ = value;
                onChanged();
                return this;
            }

            private Object message_ = "";

            /**
             * <code>string message = 2;</code>
             *
             * @return The message.
             */
            @Override
            public String getMessage() {
                Object ref = message_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string message = 2;</code>
             *
             * @return The bytes for message.
             */
            @Override
            public com.google.protobuf.ByteString
            getMessageBytes() {
                Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message = 2;</code>
             *
             * @param value The message to set.
             * @return This builder for chaining.
             */
            public Builder setMessage(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>string message = 2;</code>
             *
             * @param value The bytes for message to set.
             * @return This builder for chaining.
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Point2PointMessage)
        }

        // @@protoc_insertion_point(class_scope:Point2PointMessage)
        private static final Point2PointMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Point2PointMessage();
        }

        public static Point2PointMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Point2PointMessage>
                PARSER = new com.google.protobuf.AbstractParser<Point2PointMessage>() {
            @Override
            public Point2PointMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Point2PointMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Point2PointMessage> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Point2PointMessage> getParserForType() {
            return PARSER;
        }

        @Override
        public Point2PointMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Point2PointMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Point2PointMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\030Point2PointMessage.proto\"S\n\022Point2Poin" +
                        "tMessage\022\022\n\njava_class\030\177 \001(\014\022\030\n\020targetAd" +
                        "dressKey\030\001 \001(\t\022\017\n\007message\030\002 \001(\tb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Point2PointMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Point2PointMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Point2PointMessage_descriptor,
                new String[]{"JavaClass", "TargetAddressKey", "Message",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
